#!/usr/bin/env bash
set -euo pipefail

go build ./...
go vet ./...
go test -race -count=1 ./...

if ! command -v golangci-lint >/dev/null 2>&1; then
  echo "golangci-lint not installed; run \`make lint\` or \`go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2\`"
  exit 1
fi
golangci-lint run --timeout=5m ./...
